### ISSUE TITLE
训练完的模型怎么使用

### ISSUE THREAD

**Issue by yunchangxiaoguan** [minivision-ai/Silent-Face-Anti-Spoofing#52]
训练完的模型使用时报错，运行test.py在win10报错
Traceback (most recent call last):
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 189, in nti
    n = int(s.strip() or "0", 8)
ValueError: invalid literal for int() with base 8: '_rebuil'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 2299, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 1093, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 1035, in frombuf
    chksum = nti(buf[148:156])
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 191, in nti
    raise InvalidHeaderError("invalid header")
tarfile.InvalidHeaderError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\silence\lib\site-packages\torch\serialization.py", line 555, in _load
    return legacy_load(f)
  File "D:\anaconda3\envs\silence\lib\site-packages\torch\serialization.py", line 466, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "D:\anaconda3\envs\silence\lib\tarfile.py", line 2311, in next
    raise ReadError(str(e))
tarfile.ReadError: invalid header

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/2020project/Silent-Face-Anti-Spoofing-master/test.py", line 110, in <module>
    test(args.image_name, args.model_dir, args.device_id)
  File "D:/2020project/Silent-Face-Anti-Spoofing-master/test.py", line 60, in test
    prediction += model_test.predict(img, os.path.join(model_dir, model_name))
  File "D:\2020project\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 87, in predict
    self._load_model(model_path)
  File "D:\2020project\Silent-Face-Anti-Spoofing-master\src\anti_spoof_predict.py", line 67, in _load_model
    state_dict = torch.load(model_path, map_location=self.device)
  File "D:\anaconda3\envs\silence\lib\site-packages\torch\serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda3\envs\silence\lib\site-packages\torch\serialization.py", line 559, in _load
    raise RuntimeError("{} is a zip archive (did you mean to use torch.jit.load()?)".format(f.name))
RuntimeError: ./resources/anti_spoof_models\1_80x80_MiniFASNetV1.pth is a zip archive (did you mean to use torch.jit.load()?)

在linux报错
python test.py 
Traceback (most recent call last):
  File "test.py", line 109, in <module>
    test(args.image_name, args.model_dir, args.device_id)
  File "test.py", line 59, in test
    prediction += model_test.predict(img, os.path.join(model_dir, model_name))
  File "/ywcx/guanxiao/Silent-Face-Anti-Spoofing/src/anti_spoof_predict.py", line 87, in predict
    self._load_model(model_path)
  File "/ywcx/guanxiao/Silent-Face-Anti-Spoofing/src/anti_spoof_predict.py", line 64, in _load_model
    self.model = MODEL_MAPPING[model_type](conv6_kernel=self.kernel_size).to(self.device)
KeyError: 'model'

请问这个要怎么解决，在linux我改了模型的后缀，MODEL_MAPPING = {
    'MiniFASNetV1': MiniFASNetV1,
    'MiniFASNetV2': MiniFASNetV2,
    'MiniFASNetV1SE':MiniFASNetV1SE,
    'MiniFASNetV2SE':MiniFASNetV2SE
}
这四个都试了，都说模型不对，默认训练的是什么模型啊

**Comment by zhuyingSeu** [comment]
看看模型训练的配置
